### ISSUE TITLE
Unhandled error. ImportError: No module named nmap

### ISSUE THREAD

**Issue by CarlosAMolina** [securipy/nmap-scan#26]
If python-nmap is not installed. Example:
- sudo apt-get install python-pip nmap
- sudo pip install python-nmap

An unhandled error occurs (ImportError: No module named nmap).

**Comment by CarlosAMolina** [comment]
Error example
##########

Opciones Disponibles:

1 - nmap-scan

JarJar >> 1
_Traceback (most recent call last):
  File "__init__.py", line 178, in <module>
    module.add(salida, translate, log, 'installer', readline)
  File "modules/nmap-scan/ini_nmap-scan.py", line 30, in __init__
    from scan import Scan
  File "modules/nmap-scan/model/scan.py", line 13, in <module>
    import sys, nmap, time, os.path
ImportError: No module named nmap_
1 - nmap-scan
JarJar >> exit

**Comment by 0xtaf** [comment]
sudo pip3 install python-nmap 

solved my problem
